version: 2
jobs:

  test:
    docker:
      - image: continuumio/miniconda3 # python:3.6 works

    steps:
      - run:
          name: Install httptools
          command: |
            pip install httptools

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - test
